version: "3.7"
services:
  snownix_pg:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - snownix_pg_data:/var/lib/postgresql/data

volumes:
  snownix_pg_data:
  